#!/usr/bin/expect -f

set result_code 255

spawn ./run-demo.sh
match_max 1000000

sleep 6

expect "Terminate Plymouth Boot"
send "\r"
# Login as root
expect "login:"
send "root\r"
expect {
    "#" {}
    "failed" { set result_code 1 }
  }

sleep 60

send "kubectl get pods\r"

send "kubectl create -f /vm.json\r"
expect {
    "vm \"testvm\" created" {}
    "refused" { set result_code 2 }
  }

sleep 5

send "virsh domstate testvm\r"
expect {
    "running" { set result_code 0 }
  }

send "init 0\r"
sleep 5
close

wait

exit $result_code
