#!/bin/bash
# usage: prepare-host (kubernetes|origin) $VERSION

set -e

kubernetes() {
  local CVER=$1

  curl -Lo kubectl \
    https://storage.googleapis.com/kubernetes-release/release/v$CVER/bin/linux/amd64/kubectl

  sudo install -m a+x kubectl /usr/local/bin

  curl -L \
    https://github.com/kubernetes-incubator/cri-tools/releases/download/v1.11.1/crictl-v1.11.1-linux-amd64.tar.gz \
    | tar zx crictl

  sudo install -m a+x crictl /usr/local/bin

  curl -Lo minikube \
    https://storage.googleapis.com/minikube/releases/v0.28.2/minikube-linux-amd64

  sudo install -m a+x minikube /usr/local/bin
}

origin() {
  local CVER=$1

  sudo sed -i 's%DOCKER_OPTS=\"%DOCKER_OPTS=\"--insecure-registry 172.30.0.0/16 %' /etc/default/docker
  sudo systemctl restart docker

  curl -L \
    https://github.com/openshift/origin/releases/download/v$CVER/openshift-origin-client-tools-v3.10.0-dd10d17-linux-64bit.tar.gz \
    | tar zx --strip-components=1 openshift-origin-client-tools-v3.10.0-dd10d17-linux-64bit/oc

  sudo install -m a+x oc /usr/local/bin
  # For compatibility
  sudo ln -sf /usr/local/bin/oc /usr/local/bin/kubectl
}

$1 $2
