#!/bin/bash
# usage: start-cluster (kubernetes|origin) $VERSION

set -e

kubernetes() {
  local VER=$1

  export MINIKUBE_WANTUPDATENOTIFICATION=false
  export MINIKUBE_WANTREPORTERRORPROMPT=false
  export MINIKUBE_HOME=$HOME
  export CHANGE_MINIKUBE_NONE_USER=true
  mkdir -p $HOME/.kube
  touch $HOME/.kube/config

  export KUBECONFIG=$HOME/.kube/config

  sudo -E minikube start \
    --vm-driver=none \
    --kubernetes-version=v$VER \
    --feature-gates=DevicePlugins=true

  minikube update-context
}

origin() {
  local VER=$1

  oc version
  oc cluster up --skip-registry-check --enable=-router,-sample-templates
  oc cluster down
  sed -i "/kind/ a\kubeletArguments:\n  feature-gates:\n  - DevicePlugins=true" $PWD/openshift.local.clusterup/node/node-config.yaml
  oc cluster up --skip-registry-check

  oc login -u system:admin

  # Workaround for https://github.com/openshift/origin/pull/20351
  KUBELET_ROOTFS=$(sudo docker inspect $(sudo docker ps | grep kubelet | cut -d" " -f1) | jq -r ".[0].GraphDriver.Data.MergedDir" -)
  sudo mkdir -p /var/lib/kubelet/device-plugins $KUBELET_ROOTFS/var/lib/kubelet/device-plugins
  sudo mount -o bind $KUBELET_ROOTFS/var/lib/kubelet/device-plugins /var/lib/kubelet/device-plugins
  sudo ls /var/lib/kubelet/device-plugins
  #sudo mount --make-rshared $KUBELET_ROOTFS/var/lib/kubelet/device-plugins
}

$1 $2

timeout 1m bash ci/wait-pods-ok
